-- Segment data from Mewlax's RB Oak Guide (Red/Blue).
-- https://docs.google.com/document/d/1gmp-piwpfUUyxnWULjQtB2m2lzWeYc-wwsXnnbyp_RY
--
-- Gate order is NOT normal gym order: Brock → Misty → Koga → Erika,
-- then Articuno (Strength), then Moltres (Victory Road / E4 path), then Mewtwo.
-- Trade finals are never required. Version exclusives are per-version tables.

return {
  {
    id = "brock",
    badge = "BOULDERBADGE",
    leaderKey = "OPP_BROCK#1",
    label = "BROCK",
    mapHint = "PEWTER GYM",
    tips = {
      "Get Oak's PARCEL + POKéDEX before evolving your starter.",
      "Catch a spare SPEAROW on Route 22 for a later trade.",
      "Train CATERPIE/WEEDLE to Lv9 before evolving (cocoons get attack drop).",
      "Hold PIDGEY unevolved until Wing Attack (Lv28) if you want better PP.",
      "Fight gym trainers for EXP — don't talk to BROCK until this list is done.",
      "PIKACHU cannot evolve yet (no Thunderstone).",
    },
    starterRequired = true,
    add = {
      "CATERPIE", "METAPOD", "BUTTERFREE",
      "WEEDLE", "KAKUNA", "BEEDRILL",
      "PIDGEY", "PIDGEOTTO", "PIDGEOT",
      "RATTATA", "RATICATE",
      "SPEAROW", "FEAROW",
      "NIDORAN_F", "NIDORINA",
      "NIDORAN_M", "NIDORINO",
      "PIKACHU",
    },
  },
  {
    id = "misty",
    badge = "CASCADEBADGE",
    leaderKey = "OPP_MISTY#1",
    label = "MISTY",
    mapHint = "CERULEAN GYM (for CUT)",
    tips = {
      "MT. MOON has a point of no return — catch everything + both Moon Stones before the east ledge.",
      "Buy MAGIKARP on Route 4 (or wait for Old Rod later).",
      "Catch a spare ABRA on Route 24 for the MR. MIME trade.",
      "Trade SPEAROW→FARFETCH'D in Vermilion; ABRA→MR. MIME on Route 2.",
      "Clear SS Anne trainers before CUT (ship leaves forever).",
      "Skip LT. SURGE for now — CUT from MISTY unlocks the next big section.",
      "Moon Stone targets: NIDOQUEEN / NIDOKING / WIGGLYTUFF / CLEFABLE (need 4 total eventually).",
    },
    -- Moon stone: evolve as many as you can with the 2 stones in Mt Moon (guide evolves Nidos first).
    moonStonePool = { "NIDOQUEEN", "NIDOKING", "WIGGLYTUFF", "CLEFABLE" },
    moonStoneNeed = 2, -- two stones available this segment
    add = {
      "JIGGLYPUFF",
      "MAGIKARP", "GYARADOS",
      "ZUBAT", "GOLBAT",
      "GEODUDE", "GRAVELER",
      "PARAS", "PARASECT",
      "CLEFAIRY",
      "ABRA", "KADABRA",
      "FARFETCHD",
      "DROWZEE", "HYPNO",
      "DIGLETT", "DUGTRIO",
      "MR_MIME",
      -- Red exclusives in this part:
      "EKANS", "ARBOK",
      "ODDISH", "GLOOM",
      "MANKEY", "PRIMEAPE",
    },
  },
  {
    id = "koga",
    badge = "SOULBADGE",
    leaderKey = "OPP_KOGA#1",
    label = "KOGA",
    mapHint = "FUCHSIA GYM (for SURF)",
    tips = {
      "After MISTY: bike voucher, Cut for Flash HM + Old Amber + Moon Stone on Route 4.",
      "Buy stones in Celadon; finish remaining Moon Stone evolutions (4 total).",
      "Buy PORYGON (Game Corner). Skip Safari purchases you can catch later.",
      "Soft-reset in Safari (A+B+Start+Select) to save entry fees on 4% spawns.",
      "Spare POLIWHIRL→JYNX (Cerulean); SLOWBRO→LICKITUNG (Route 18 gate).",
      "Dojo: HITMONLEE or HITMONCHAN. Silph: LAPRAS. Poké Flute: both SNORLAX.",
      "Dragonite is the grind wall — Wrap helps; Surf TM is fine on Dratini.",
    },
    moonStonePool = { "NIDOQUEEN", "NIDOKING", "WIGGLYTUFF", "CLEFABLE" },
    moonStoneNeed = 4, -- all four by end of this part
    anyOf = {
      { "HITMONLEE", "HITMONCHAN" },
      { "VAPOREON", "JOLTEON", "FLAREON" },
    },
    add = {
      "VOLTORB", "ELECTRODE",
      "MACHOP", "MACHOKE",
      "ONIX",
      "GROWLITHE", "ARCANINE",
      "EEVEE",
      "PORYGON",
      "RAICHU",
      "VILEPLUME",
      "DODUO", "DODRIO",
      "GASTLY", "HAUNTER",
      "CUBONE", "MAROWAK",
      "SNORLAX",
      "SHELLDER", "CLOYSTER",
      "POLIWAG", "POLIWHIRL", "POLIWRATH",
      "GOLDEEN", "SEAKING",
      "KRABBY", "KINGLER",
      "HORSEA", "SEADRA",
      "STARYU", "STARMIE",
      "PSYDUCK", "GOLDUCK",
      "SLOWPOKE", "SLOWBRO",
      "TENTACOOL", "TENTACRUEL",
      "JYNX",
      "LICKITUNG",
      "DITTO",
      "VENONAT", "VENOMOTH",
      "DRATINI", "DRAGONAIR", "DRAGONITE",
      "EXEGGCUTE", "EXEGGUTOR",
      "RHYHORN", "RHYDON",
      "CHANSEY",
      "SCYTHER",
      "TAUROS",
      "KANGASKHAN",
      "HITMONLEE", "HITMONCHAN",
      "LAPRAS",
      "VAPOREON", "JOLTEON", "FLAREON",
    },
  },
  {
    id = "erika",
    badge = "RAINBOWBADGE",
    leaderKey = "OPP_ERIKA#1",
    label = "ERIKA",
    mapHint = "CELADON GYM (for STRENGTH)",
    tips = {
      "Guide order: KOGA before ERIKA — Strength alone only unlocks Articuno later.",
      "Surf to Power Plant (ZAPDOS + Magnemite; Electabuzz on Red).",
      "Surf south of Pallet for TANGELA; Cinnabar lab for fossils + Aerodactyl.",
      "Pokemon Mansion: Koffing/Grimer/Ponyta (+ Magmar on Blue).",
      "Seafoam: Seel/Dewgong for now (Articuno needs Strength from Erika).",
    },
    fossilPair = {
      { "OMANYTE", "OMASTAR" },
      { "KABUTO", "KABUTOPS" },
    },
    add = {
      "MAGNEMITE", "MAGNETON",
      "ELECTABUZZ",
      "ZAPDOS",
      "TANGELA",
      "AERODACTYL",
      "OMANYTE", "OMASTAR",
      "KABUTO", "KABUTOPS",
      "KOFFING", "WEEZING",
      "GRIMER", "MUK",
      "PONYTA", "RAPIDASH",
      "SEEL", "DEWGONG",
    },
  },
  {
    id = "articuno",
    badge = nil, -- not a gym gate; tracked after Erika
    leaderKey = nil,
    label = "ARTICUNO",
    mapHint = "SEAFOAM (needs STRENGTH)",
    tips = {
      "After ERIKA, use Strength on Seafoam boulders to reach ARTICUNO.",
      "No other badge by itself unlocks a new catch here.",
    },
    add = {
      "ARTICUNO",
    },
    requireBadge = "RAINBOWBADGE", -- only meaningful once Erika is beaten
  },
  {
    id = "moltres",
    badge = nil,
    leaderKey = nil,
    label = "MOLTRES",
    mapHint = "VICTORY ROAD (pre-E4)",
    tips = {
      "Finish LT. SURGE, SABRINA, BLAINE, GIOVANNI, then Victory Road.",
      "Catch MOLTRES on the way through Victory Road before the Elite Four.",
    },
    add = {
      "MOLTRES",
    },
    gateEliteFour = true,
  },
  {
    id = "mewtwo",
    badge = nil,
    leaderKey = nil,
    label = "MEWTWO",
    mapHint = "CERULEAN CAVE (post-game)",
    tips = {
      "After becoming Champion, Surf to Cerulean Cave for MEWTWO.",
      "Ensure your current PC box has space before the trip!",
      "Trade evolutions (Alakazam/Machamp/Golem/Gengar), version exclusives,",
      "other starters / Hitmon / Eevee / fossil choices, and Mew stay missing.",
    },
    add = {
      "MEWTWO",
    },
    postGame = true,
  },
}
