-- Cumulative species additions for Pokémon Red (Professor Oak Challenge).
-- Each segment lists NEW species reasonably obtainable before that gym.
-- Gate = union of all segments up to the next undefeated badge.
--
-- Trade finals (ALAKAZAM, MACHAMP, GOLEM, GENGAR) are optional (see main.lua).
-- One-of choices (starter, dojo, fossil, Eevee) use special rules in checklist.
-- v0.1 best-effort — soft mode is the default so list gaps never soft-lock you.

return {
  {
    id = "brock",
    badge = "BOULDERBADGE",
    leaderKey = "OPP_BROCK#1",
    label = "BROCK",
    mapHint = "PEWTER GYM",
    add = {
      "CATERPIE", "METAPOD", "BUTTERFREE",
      "WEEDLE", "KAKUNA", "BEEDRILL",
      "PIDGEY", "PIDGEOTTO", "PIDGEOT",
      "RATTATA", "RATICATE",
      "SPEAROW", "FEAROW",
      "NIDORAN_F", "NIDORINA",
      "NIDORAN_M", "NIDORINO",
      "PIKACHU",
      "MANKEY", "PRIMEAPE",
    },
    starterRequired = true,
  },
  {
    id = "misty",
    badge = "CASCADEBADGE",
    leaderKey = "OPP_MISTY#1",
    label = "MISTY",
    mapHint = "CERULEAN GYM",
    add = {
      "SANDSHREW", "SANDSLASH",
      "JIGGLYPUFF", "WIGGLYTUFF",
      "ZUBAT", "GOLBAT",
      "GEODUDE", "GRAVELER",
      "PARAS", "PARASECT",
      "CLEFAIRY", "CLEFABLE",
      "NIDOQUEEN", "NIDOKING",
      "MAGIKARP", "GYARADOS",
    },
  },
  {
    id = "surge",
    badge = "THUNDERBADGE",
    leaderKey = "OPP_LT_SURGE#1",
    label = "LT.SURGE",
    mapHint = "VERMILION GYM",
    add = {
      "BELLSPROUT", "WEEPINBELL", "VICTREEBEL",
      "ABRA", "KADABRA",
      "VENONAT",
      "PSYDUCK", "GOLDUCK",
      "GROWLITHE", "ARCANINE",
      "POLIWAG", "POLIWHIRL", "POLIWRATH",
      "TENTACOOL", "TENTACRUEL",
      "DIGLETT", "DUGTRIO",
      "DROWZEE", "HYPNO",
      "KRABBY", "KINGLER",
      "VOLTORB", "ELECTRODE",
      "FARFETCHD",
      "SHELLDER", "CLOYSTER",
      "KRABBY",
      "HORSEA", "SEADRA",
      "GOLDEEN", "SEAKING",
      "STARYU", "STARMIE",
      "MAGNEMITE", "MAGNETON",
    },
  },
  {
    id = "erika",
    badge = "RAINBOWBADGE",
    leaderKey = "OPP_ERIKA#1",
    label = "ERIKA",
    mapHint = "CELADON GYM",
    add = {
      "ODDISH", "GLOOM", "VILEPLUME", -- Game Corner / trades / late; included for Red completeness
      "MEOWTH", "PERSIAN",
      "MANKEY",
      "GROWLITHE",
      "CUBONE", "MAROWAK",
      "GASTLY", "HAUNTER",
      "MACHOP", "MACHOKE",
      "ONIX",
      "VOLTORB",
      "EXEGGCUTE", "EXEGGUTOR",
      "KOFFING", "WEEZING",
      "RHYHORN", "RHYDON",
      "CHANSEY",
      "TANGELA",
      "KANGASKHAN",
      "HORSEA",
      "GOLDEEN",
      "MR_MIME",
      "JYNX",
      "ELECTABUZZ",
      "MAGMAR",
      "PINSIR",
      "TAUROS",
      "EEVEE",
      "PORYGON",
      "OMANYTE", "OMASTAR",
      "KABUTO", "KABUTOPS",
      "AERODACTYL",
      "HITMONLEE", "HITMONCHAN",
      "LICKITUNG",
      "SCYTHER",
      "LAPRAS",
      "DITTO",
      "VAPOREON", "JOLTEON", "FLAREON",
      "RAICHU",
      "VENOMOTH",
    },
    anyOf = {
      { "HITMONLEE", "HITMONCHAN" },
      { "VAPOREON", "JOLTEON", "FLAREON" },
    },
    -- Fossil: require exactly one complete line
    fossilPair = {
      { "OMANYTE", "OMASTAR" },
      { "KABUTO", "KABUTOPS" },
    },
  },
  {
    id = "koga",
    badge = "SOULBADGE",
    leaderKey = "OPP_KOGA#1",
    label = "KOGA",
    mapHint = "FUCHSIA GYM",
    add = {
      "DODUO", "DODRIO",
      "EXEGGCUTE", "EXEGGUTOR",
      "RHYHORN", "RHYDON",
      "CHANSEY",
      "TANGELA",
      "KANGASKHAN",
      "SCYTHER",
      "PINSIR",
      "TAUROS",
      "DRATINI", "DRAGONAIR", "DRAGONITE",
    },
  },
  {
    id = "sabrina",
    badge = "MARSHBADGE",
    leaderKey = "OPP_SABRINA#1",
    label = "SABRINA",
    mapHint = "SAFFRON GYM",
    add = {
      "SNORLAX",
    },
  },
  {
    id = "blaine",
    badge = "VOLCANOBADGE",
    leaderKey = "OPP_BLAINE#1",
    label = "BLAINE",
    mapHint = "CINNABAR GYM",
    add = {
      "ARTICUNO",
      "ZAPDOS",
      "MOLTRES",
      "OMANYTE", "OMASTAR",
      "KABUTO", "KABUTOPS",
      "AERODACTYL",
      "MAGMAR",
    },
  },
  {
    id = "giovanni",
    badge = "EARTHBADGE",
    leaderKey = "OPP_GIOVANNI#3",
    label = "GIOVANNI",
    mapHint = "VIRIDIAN GYM",
    add = {
      "MEWTWO",
    },
  },
}
